[build]
builder = "nixpacks"

# Explicitly set this as a Python project
[build.runtime]
name = "python"
version = "3.11"

# Build commands - explicitly skip Node.js stuff
[build.commands]
build = "pip install -r requirements.txt"

# Deploy commands
[deploy]
startCommand = "python manage.py migrate && gunicorn config.wsgi:application"

# Environment variables
[env]
DISABLE_COLLECTSTATIC = "1"
PYTHON_VERSION = "3.11.0"