# Generated by Django 5.2.4 on 2025-09-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_comment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
